// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClThDNOqpn5IqZztNEkEZ0ZAYW1Jk1vT0',
    appId: '1:150025815077:web:44b89d7567991893beabcc',
    messagingSenderId: '150025815077',
    projectId: 'my-voter-app-data',
    authDomain: 'my-voter-app-data.firebaseapp.com',
    databaseURL: 'https://my-voter-app-data-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-voter-app-data.firebasestorage.app',
    measurementId: 'G-TWMD4X6DRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT-PdH1_fabjM1Estc3L8yomc4OttZS7A',
    appId: '1:150025815077:android:3dfa126c7ce9cd83beabcc',
    messagingSenderId: '150025815077',
    projectId: 'my-voter-app-data',
    databaseURL: 'https://my-voter-app-data-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-voter-app-data.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS0898cfp-7LHxRrpk9Ndx2Fjd2rdGWK4',
    appId: '1:150025815077:ios:ac43e6214a1bcd83beabcc',
    messagingSenderId: '150025815077',
    projectId: 'my-voter-app-data',
    databaseURL: 'https://my-voter-app-data-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-voter-app-data.firebasestorage.app',
    iosBundleId: 'com.sajidpatel.sajidpatelVoterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS0898cfp-7LHxRrpk9Ndx2Fjd2rdGWK4',
    appId: '1:150025815077:ios:ac43e6214a1bcd83beabcc',
    messagingSenderId: '150025815077',
    projectId: 'my-voter-app-data',
    databaseURL: 'https://my-voter-app-data-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-voter-app-data.firebasestorage.app',
    iosBundleId: 'com.sajidpatel.sajidpatelVoterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClThDNOqpn5IqZztNEkEZ0ZAYW1Jk1vT0',
    appId: '1:150025815077:web:ed6d30ff4896bd7cbeabcc',
    messagingSenderId: '150025815077',
    projectId: 'my-voter-app-data',
    authDomain: 'my-voter-app-data.firebaseapp.com',
    databaseURL: 'https://my-voter-app-data-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-voter-app-data.firebasestorage.app',
    measurementId: 'G-8BWC304E1G',
  );
}
